name: tinylogs
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  sqflite: ^2.3.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onboarding_illustration.png
    - assets/images/message_header_icon.png
    - assets/images/arrow_left.png
    - assets/images/arrow_drop_down.png
    - assets/images/icon_share.png
    - assets/images/icon_delete.png
    - assets/images/icon_ask_hint.png
    - assets/images/icon_edit_fab.png
    - assets/images/icon_today_normal.png
    - assets/images/icon_today_selected.png
    - assets/images/icon_edit_fab.png
    - assets/images/icon_insights_normal.png
    - assets/images/icon_insights_selected.png
    - assets/images/icon_notes_normal.png
    - assets/images/icon_notes_selected.png

fonts:
  - family: SF Pro Text
    fonts:
      - asset: fonts/SFProText-Regular.ttf
  - family: SF Pro Display
    fonts:
      - asset: fonts/SFProDisplay-Regular.ttf