name: tinylogs
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+102

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  sqflite: ^2.3.0
  sqflite_common_ffi: 2.3.2
  shared_preferences: ^2.0.6
  flutter_local_notifications: 16.3.0
  flutter_timezone: 1.0.8
  flutter_native_splash: 2.3.9
  permission_handler: 11.1.0
  share_plus: 7.2.1
  screenshot: 2.1.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/onboarding_illustration.png
    - assets/images/message_header_icon.png
    - assets/images/arrow_left.png
    - assets/images/arrow_drop_down.png
    - assets/images/icon_share.png
    - assets/images/icon_delete.png
    - assets/images/icon_ask_hint.png
    - assets/images/icon_edit_fab.png
    - assets/images/icon_today_normal.png
    - assets/images/icon_today_selected.png
    - assets/images/icon_edit_fab.png
    - assets/images/icon_insights_normal.png
    - assets/images/icon_insights_selected.png
    - assets/images/icon_notes_normal.png
    - assets/images/icon_notes_selected.png
    - assets/images/background_logs_month_separator.png
    - assets/images/icon_today_empty_state.png
    - assets/images/icon_cloud_with_sun_and_rain.png
    - assets/images/icon_medal.png
    - assets/images/icon_medal_dark.png
    - assets/images/icon_thumbs_up.png
    - assets/images/icon_cross.png
    - assets/images/icon_settings.png
    - assets/images/icon_star.png
    - assets/images/icon_mini_cross.png
    - assets/images/icon_chevron_right.png

fonts:
  - family: SF Pro Text
    fonts:
      - asset: fonts/SFProText-Regular.ttf
  - family: SF Pro Display
    fonts:
      - asset: fonts/SFProDisplay-Regular.ttf